name: Maven Package to Hycraft Nexus

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Java for publishing to Hycraft Nexus
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  server-id: hycraft-repo
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - name: Publish to Hycraft Nexus
              run: mvn --batch-mode deploy -Ppublish
              env:
                  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
